const config = {
  url: 'http://localhost:4000',
  token: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJmaXJzdE5hbWUiOiJTYW5qYXkiLCJsYXN0TmFtZSI6Ik5lbGx1dGxhIiwiZW1haWwiOiJzYW5qYXkubmVsbHV0bGFAZmlzc2lvbmxhYnMuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkZDdRUEJRdW4xaEhPSjIxNG9NSGhmZVQuVXNoQ2JXd3R5ZGVXclBId09ySWRvRzVUYkhreUsiLCJjcmVhdGVkQXQiOiIyMDIyLTExLTI1VDExOjI1OjM1LjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDIyLTExLTI1VDExOjI1OjM1LjAwMFoifSwiaWF0IjoxNjY5Mzg0NzU3fQ.lbRe-m7X2QwbcszS3Opjf5ebwUrciAf9gFbFH12CgbA"
};

export default config;